import type { Metadata } from "next"
import "./globals.css"
import { Poppins, Quicksand } from "next/font/google"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
})
const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-quicksand",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${quicksand.variable} antialiased ${poppins.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
